# Generated by Django 4.1.3 on 2022-11-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_author_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='related_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
