# Generated by Django 4.1.3 on 2022-11-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='related_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.test'),
        ),
    ]
