# Generated by Django 4.1.3 on 2022-11-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='related_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course', to_field='course_name'),
        ),
    ]
