# Generated by Django 4.1.3 on 2022-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_course_name_alter_test_related_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
