# Generated by Django 4.1.3 on 2022-11-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_test_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='related_course',
            new_name='related_course_name',
        ),
        migrations.AlterField(
            model_name='question',
            name='related_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.test', to_field='test_name'),
        ),
    ]
