# Generated by Django 4.1.3 on 2022-11-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
