# Generated by Django 4.1.3 on 2022-11-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_group_studentuser_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
